### ISSUE TITLE
Сквозь непрозрачные двойные эирлоки можно смотреть.

### ISSUE THREAD

**Issue by Archibald125** [TheArkStation/Ark-Station#27]

**Comment by SolatK** [comment]
Бейцы говорят что это не фиксится без костылей так как есть ограничения со стороны бьенда. Так что или там нужно ставить прозрачные шлюзы, или два одинарных

**Comment by SolatK** [comment]
Если очень надо - я могу попробовать чтобы два обычных эйрлока "слипались в один" и открывались вместе
