### ISSUE TITLE
Найти возможность убрать наш код из audible.dm оригинальных файлов

### ISSUE THREAD

**Issue by Archibald125** [TheArkStation/Ark-Station#34]
=

**Comment by Spin2sin** [comment]
Актуально? И что там такого "нашего"?

**Comment by Archibald125** [comment]
Уже и не вспомню. Но, думаю, я что-то поменял на фоне внесения звукоэмоутов инфинити и перевода.

**Comment by Spin2sin** [comment]
Вспомнишь - откроешь заново с нормальным объяснением.
