### ISSUE TITLE
Баг с eject из бодисканера

### ISSUE THREAD

**Issue by Archibald125** [TheArkStation/Ark-Station#36]
#### Это багрепорт, или же это предложение фичи?
- [x] Баг
- [ ] Фича

#### Описание предложения \ проблемы
При до конца неустановленных обстоятельствах, если положить существо в бодисканер (опционально просканировав его), то потом его невозможно достать.

#### Разница между тем, как оно работает, и как оно должно
--

#### Как воспроизвести
Необходимо положить существо в сканер, (просканировать его, а иногда это и не требуется), после этого попытаться его достать.

В чат выдаст: 
Sorry, the following is not valid: Body-Scanner-(the-unknown)
usage: Eject-Body-Scanner obj

Несколько раз мне каким-то мистическим образом помог Fix NanoUI, но более воспроизвести это не выходит.

#### Версия Бьёнда

513.

**Comment by Tech3434** [comment]
С enter body scanner тоже самое, хотя выйти оттуда можно просто шагнув куда-либо, если в сознании.

**Comment by Tech3434** [comment]
Пофикшено в самой новой версии Бульёна.
