### ISSUE TITLE
Добавить безбилетника

### ISSUE THREAD

**Issue by Archibald125** [TheArkStation/Ark-Station#41]

**Comment by Spin2sin** [comment]
Актуально? К какой карте?

**Comment by Archibald125** [comment]
Кастельнау. Все иссуи по Кастельнау.

**Comment by Spin2sin** [comment]
Но у нас же Либерти планируется.

**Comment by Archibald125** [comment]
Тогда можно закрыть, надеясь на то, что Рекс доделает Либерти.
