### ISSUE TITLE
Лестницы вертикальные не соединены.

### ISSUE THREAD

**Issue by wadangel** [TheArkStation/Ark-Station#42]
#### *Подробное описание проблемы*
В некоторых местах не соединены лестницы. Грубо говоря, я могу слезть по ней с верхней палубы на нижнюю, но наоборот у меня не выйдет, потому что The ladder is incomplete and can't be climbed.
#### *Что должно было произойти*
Всё должно быть нормально.
#### *Что произошло на самом деле*
Ничего :(
#### *Как повторить*
Слезть-залезть по разным лестницам.
#### *Дополнительная информация:*
Дальше списком координаты:

- 95, 63, 2 (не соединена с верхней)
- 95, 93, 2 (не соединена с верхней)
- 90, 90, 3 (нижней лестницы просто нет)

![](https://i.gyazo.com/6b16ac35a9a950d178fa32a52d1417fb.png)

- 71, 91, 1 (не соединена с верхней)
- 71, 91, 2 (не соединена с нижней и верхней)
- 51, 82, 2 (не соединена с верхней)
- 59, 66, 2 (не соединена с верхней)
- 71, 65, 2 (не соединена с верхней)

Это всё, кажется.

**Comment by Tea-Primoris** [comment]
- 95, 63, 2 (не соединена с верхней)
- 95, 93, 2 (не соединена с верхней)
- ~~90, 90, 3 (нижней лестницы просто нет)~~
- 71, 91, 1 (не соединена с верхней)
- 71, 91, 2 (не соединена с нижней и верхней)
- 51, 82, 2 (не соединена с верхней)
- 59, 66, 2 (не соединена с верхней)
- 71, 65, 2 (не соединена с верхней)

**Comment by Tea-Primoris** [comment]
![image](https://user-images.githubusercontent.com/32336957/61159340-5f5ea080-a504-11e9-9492-a20db429c018.png)
**ДЕЛО СДЕЛАНО**
