### ISSUE TITLE
Починить дефолтный доступ для дек мененджмента

### ISSUE THREAD

**Issue by Archibald125** [TheArkStation/Ark-Station#79]

**Comment by Tea-Primoris** [comment]
Больше инфы

**Comment by Archibald125** [comment]
В коде deck_management программы задаётся глобальная переменная default_access, которая определяет доступ, необходимый для администрирования программы. Я не могу перезадать его в наших файлах, не трогая основные, так как будет ошибка с двойным указанием переменной.
